import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "./components/ui/toaster";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Niger Gym",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/icon.png" sizes="256x256" />
      </head>
      <ClerkProvider>
        <body className={inter.className}>
          {/* <PreventZoom />  */}
          {children}
          <SpeedInsights />
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
